/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiSitesRouteImport } from './routes/api/sites'
import { Route as PublicSlugRouteImport } from './routes/public.$slug'
import { Route as ApiAdminAccessRouteImport } from './routes/api/admin.access'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiPublicSlugRouteImport } from './routes/api/public.$slug'
import { Route as ApiSitesSiteIdRouteImport } from './routes/api/sites.$siteId'
import { Route as ApiPublicSlugRealtimeRouteImport } from './routes/api/public.$slug.realtime'
import { Route as ApiPublicSlugSourceDetailsRouteImport } from './routes/api/public.$slug.source-details'
import { Route as ApiSitesSiteIdActivityRouteImport } from './routes/api/sites.$siteId.activity'
import { Route as ApiSitesSiteIdDevicesRouteImport } from './routes/api/sites.$siteId.devices'
import { Route as ApiSitesSiteIdLocationsRouteImport } from './routes/api/sites.$siteId.locations'
import { Route as ApiSitesSiteIdPagesRouteImport } from './routes/api/sites.$siteId.pages'
import { Route as ApiSitesSiteIdPublicViewRouteImport } from './routes/api/sites.$siteId.public-view'
import { Route as ApiSitesSiteIdSourceDetailsRouteImport } from './routes/api/sites.$siteId.source-details'
import { Route as ApiSitesSiteIdSourcesRouteImport } from './routes/api/sites.$siteId.sources'
import { Route as ApiSitesSiteIdSummaryRouteImport } from './routes/api/sites.$siteId.summary'
import { Route as ApiSitesSiteIdTimeseriesRouteImport } from './routes/api/sites.$siteId.timeseries'
import { Route as ApiSitesSiteIdRealtimeWsRouteImport } from './routes/api/sites.$siteId.realtime.ws'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitesRoute = ApiSitesRouteImport.update({
  id: '/api/sites',
  path: '/api/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSlugRoute = PublicSlugRouteImport.update({
  id: '/public/$slug',
  path: '/public/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccessRoute = ApiAdminAccessRouteImport.update({
  id: '/api/admin/access',
  path: '/api/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlugRoute = ApiPublicSlugRouteImport.update({
  id: '/api/public/$slug',
  path: '/api/public/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitesSiteIdRoute = ApiSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => ApiSitesRoute,
} as any)
const ApiPublicSlugRealtimeRoute = ApiPublicSlugRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => ApiPublicSlugRoute,
} as any)
const ApiPublicSlugSourceDetailsRoute =
  ApiPublicSlugSourceDetailsRouteImport.update({
    id: '/source-details',
    path: '/source-details',
    getParentRoute: () => ApiPublicSlugRoute,
  } as any)
const ApiSitesSiteIdActivityRoute = ApiSitesSiteIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdDevicesRoute = ApiSitesSiteIdDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdLocationsRoute = ApiSitesSiteIdLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdPagesRoute = ApiSitesSiteIdPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdPublicViewRoute =
  ApiSitesSiteIdPublicViewRouteImport.update({
    id: '/public-view',
    path: '/public-view',
    getParentRoute: () => ApiSitesSiteIdRoute,
  } as any)
const ApiSitesSiteIdSourceDetailsRoute =
  ApiSitesSiteIdSourceDetailsRouteImport.update({
    id: '/source-details',
    path: '/source-details',
    getParentRoute: () => ApiSitesSiteIdRoute,
  } as any)
const ApiSitesSiteIdSourcesRoute = ApiSitesSiteIdSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdSummaryRoute = ApiSitesSiteIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ApiSitesSiteIdRoute,
} as any)
const ApiSitesSiteIdTimeseriesRoute =
  ApiSitesSiteIdTimeseriesRouteImport.update({
    id: '/timeseries',
    path: '/timeseries',
    getParentRoute: () => ApiSitesSiteIdRoute,
  } as any)
const ApiSitesSiteIdRealtimeWsRoute =
  ApiSitesSiteIdRealtimeWsRouteImport.update({
    id: '/realtime/ws',
    path: '/realtime/ws',
    getParentRoute: () => ApiSitesSiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/public/$slug': typeof PublicSlugRoute
  '/api/admin/access': typeof ApiAdminAccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$slug': typeof ApiPublicSlugRouteWithChildren
  '/api/sites/$siteId': typeof ApiSitesSiteIdRouteWithChildren
  '/api/public/$slug/realtime': typeof ApiPublicSlugRealtimeRoute
  '/api/public/$slug/source-details': typeof ApiPublicSlugSourceDetailsRoute
  '/api/sites/$siteId/activity': typeof ApiSitesSiteIdActivityRoute
  '/api/sites/$siteId/devices': typeof ApiSitesSiteIdDevicesRoute
  '/api/sites/$siteId/locations': typeof ApiSitesSiteIdLocationsRoute
  '/api/sites/$siteId/pages': typeof ApiSitesSiteIdPagesRoute
  '/api/sites/$siteId/public-view': typeof ApiSitesSiteIdPublicViewRoute
  '/api/sites/$siteId/source-details': typeof ApiSitesSiteIdSourceDetailsRoute
  '/api/sites/$siteId/sources': typeof ApiSitesSiteIdSourcesRoute
  '/api/sites/$siteId/summary': typeof ApiSitesSiteIdSummaryRoute
  '/api/sites/$siteId/timeseries': typeof ApiSitesSiteIdTimeseriesRoute
  '/api/sites/$siteId/realtime/ws': typeof ApiSitesSiteIdRealtimeWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/public/$slug': typeof PublicSlugRoute
  '/api/admin/access': typeof ApiAdminAccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$slug': typeof ApiPublicSlugRouteWithChildren
  '/api/sites/$siteId': typeof ApiSitesSiteIdRouteWithChildren
  '/api/public/$slug/realtime': typeof ApiPublicSlugRealtimeRoute
  '/api/public/$slug/source-details': typeof ApiPublicSlugSourceDetailsRoute
  '/api/sites/$siteId/activity': typeof ApiSitesSiteIdActivityRoute
  '/api/sites/$siteId/devices': typeof ApiSitesSiteIdDevicesRoute
  '/api/sites/$siteId/locations': typeof ApiSitesSiteIdLocationsRoute
  '/api/sites/$siteId/pages': typeof ApiSitesSiteIdPagesRoute
  '/api/sites/$siteId/public-view': typeof ApiSitesSiteIdPublicViewRoute
  '/api/sites/$siteId/source-details': typeof ApiSitesSiteIdSourceDetailsRoute
  '/api/sites/$siteId/sources': typeof ApiSitesSiteIdSourcesRoute
  '/api/sites/$siteId/summary': typeof ApiSitesSiteIdSummaryRoute
  '/api/sites/$siteId/timeseries': typeof ApiSitesSiteIdTimeseriesRoute
  '/api/sites/$siteId/realtime/ws': typeof ApiSitesSiteIdRealtimeWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/sites': typeof ApiSitesRouteWithChildren
  '/public/$slug': typeof PublicSlugRoute
  '/api/admin/access': typeof ApiAdminAccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$slug': typeof ApiPublicSlugRouteWithChildren
  '/api/sites/$siteId': typeof ApiSitesSiteIdRouteWithChildren
  '/api/public/$slug/realtime': typeof ApiPublicSlugRealtimeRoute
  '/api/public/$slug/source-details': typeof ApiPublicSlugSourceDetailsRoute
  '/api/sites/$siteId/activity': typeof ApiSitesSiteIdActivityRoute
  '/api/sites/$siteId/devices': typeof ApiSitesSiteIdDevicesRoute
  '/api/sites/$siteId/locations': typeof ApiSitesSiteIdLocationsRoute
  '/api/sites/$siteId/pages': typeof ApiSitesSiteIdPagesRoute
  '/api/sites/$siteId/public-view': typeof ApiSitesSiteIdPublicViewRoute
  '/api/sites/$siteId/source-details': typeof ApiSitesSiteIdSourceDetailsRoute
  '/api/sites/$siteId/sources': typeof ApiSitesSiteIdSourcesRoute
  '/api/sites/$siteId/summary': typeof ApiSitesSiteIdSummaryRoute
  '/api/sites/$siteId/timeseries': typeof ApiSitesSiteIdTimeseriesRoute
  '/api/sites/$siteId/realtime/ws': typeof ApiSitesSiteIdRealtimeWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collect'
    | '/login'
    | '/admin/users'
    | '/api/sites'
    | '/public/$slug'
    | '/api/admin/access'
    | '/api/auth/$'
    | '/api/public/$slug'
    | '/api/sites/$siteId'
    | '/api/public/$slug/realtime'
    | '/api/public/$slug/source-details'
    | '/api/sites/$siteId/activity'
    | '/api/sites/$siteId/devices'
    | '/api/sites/$siteId/locations'
    | '/api/sites/$siteId/pages'
    | '/api/sites/$siteId/public-view'
    | '/api/sites/$siteId/source-details'
    | '/api/sites/$siteId/sources'
    | '/api/sites/$siteId/summary'
    | '/api/sites/$siteId/timeseries'
    | '/api/sites/$siteId/realtime/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collect'
    | '/login'
    | '/admin/users'
    | '/api/sites'
    | '/public/$slug'
    | '/api/admin/access'
    | '/api/auth/$'
    | '/api/public/$slug'
    | '/api/sites/$siteId'
    | '/api/public/$slug/realtime'
    | '/api/public/$slug/source-details'
    | '/api/sites/$siteId/activity'
    | '/api/sites/$siteId/devices'
    | '/api/sites/$siteId/locations'
    | '/api/sites/$siteId/pages'
    | '/api/sites/$siteId/public-view'
    | '/api/sites/$siteId/source-details'
    | '/api/sites/$siteId/sources'
    | '/api/sites/$siteId/summary'
    | '/api/sites/$siteId/timeseries'
    | '/api/sites/$siteId/realtime/ws'
  id:
    | '__root__'
    | '/'
    | '/collect'
    | '/login'
    | '/admin/users'
    | '/api/sites'
    | '/public/$slug'
    | '/api/admin/access'
    | '/api/auth/$'
    | '/api/public/$slug'
    | '/api/sites/$siteId'
    | '/api/public/$slug/realtime'
    | '/api/public/$slug/source-details'
    | '/api/sites/$siteId/activity'
    | '/api/sites/$siteId/devices'
    | '/api/sites/$siteId/locations'
    | '/api/sites/$siteId/pages'
    | '/api/sites/$siteId/public-view'
    | '/api/sites/$siteId/source-details'
    | '/api/sites/$siteId/sources'
    | '/api/sites/$siteId/summary'
    | '/api/sites/$siteId/timeseries'
    | '/api/sites/$siteId/realtime/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectRoute: typeof CollectRoute
  LoginRoute: typeof LoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiSitesRoute: typeof ApiSitesRouteWithChildren
  PublicSlugRoute: typeof PublicSlugRoute
  ApiAdminAccessRoute: typeof ApiAdminAccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicSlugRoute: typeof ApiPublicSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sites': {
      id: '/api/sites'
      path: '/api/sites'
      fullPath: '/api/sites'
      preLoaderRoute: typeof ApiSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$slug': {
      id: '/public/$slug'
      path: '/public/$slug'
      fullPath: '/public/$slug'
      preLoaderRoute: typeof PublicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/access': {
      id: '/api/admin/access'
      path: '/api/admin/access'
      fullPath: '/api/admin/access'
      preLoaderRoute: typeof ApiAdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$slug': {
      id: '/api/public/$slug'
      path: '/api/public/$slug'
      fullPath: '/api/public/$slug'
      preLoaderRoute: typeof ApiPublicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sites/$siteId': {
      id: '/api/sites/$siteId'
      path: '/$siteId'
      fullPath: '/api/sites/$siteId'
      preLoaderRoute: typeof ApiSitesSiteIdRouteImport
      parentRoute: typeof ApiSitesRoute
    }
    '/api/public/$slug/realtime': {
      id: '/api/public/$slug/realtime'
      path: '/realtime'
      fullPath: '/api/public/$slug/realtime'
      preLoaderRoute: typeof ApiPublicSlugRealtimeRouteImport
      parentRoute: typeof ApiPublicSlugRoute
    }
    '/api/public/$slug/source-details': {
      id: '/api/public/$slug/source-details'
      path: '/source-details'
      fullPath: '/api/public/$slug/source-details'
      preLoaderRoute: typeof ApiPublicSlugSourceDetailsRouteImport
      parentRoute: typeof ApiPublicSlugRoute
    }
    '/api/sites/$siteId/activity': {
      id: '/api/sites/$siteId/activity'
      path: '/activity'
      fullPath: '/api/sites/$siteId/activity'
      preLoaderRoute: typeof ApiSitesSiteIdActivityRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/devices': {
      id: '/api/sites/$siteId/devices'
      path: '/devices'
      fullPath: '/api/sites/$siteId/devices'
      preLoaderRoute: typeof ApiSitesSiteIdDevicesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/locations': {
      id: '/api/sites/$siteId/locations'
      path: '/locations'
      fullPath: '/api/sites/$siteId/locations'
      preLoaderRoute: typeof ApiSitesSiteIdLocationsRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/pages': {
      id: '/api/sites/$siteId/pages'
      path: '/pages'
      fullPath: '/api/sites/$siteId/pages'
      preLoaderRoute: typeof ApiSitesSiteIdPagesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/public-view': {
      id: '/api/sites/$siteId/public-view'
      path: '/public-view'
      fullPath: '/api/sites/$siteId/public-view'
      preLoaderRoute: typeof ApiSitesSiteIdPublicViewRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/source-details': {
      id: '/api/sites/$siteId/source-details'
      path: '/source-details'
      fullPath: '/api/sites/$siteId/source-details'
      preLoaderRoute: typeof ApiSitesSiteIdSourceDetailsRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/sources': {
      id: '/api/sites/$siteId/sources'
      path: '/sources'
      fullPath: '/api/sites/$siteId/sources'
      preLoaderRoute: typeof ApiSitesSiteIdSourcesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/summary': {
      id: '/api/sites/$siteId/summary'
      path: '/summary'
      fullPath: '/api/sites/$siteId/summary'
      preLoaderRoute: typeof ApiSitesSiteIdSummaryRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/timeseries': {
      id: '/api/sites/$siteId/timeseries'
      path: '/timeseries'
      fullPath: '/api/sites/$siteId/timeseries'
      preLoaderRoute: typeof ApiSitesSiteIdTimeseriesRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
    '/api/sites/$siteId/realtime/ws': {
      id: '/api/sites/$siteId/realtime/ws'
      path: '/realtime/ws'
      fullPath: '/api/sites/$siteId/realtime/ws'
      preLoaderRoute: typeof ApiSitesSiteIdRealtimeWsRouteImport
      parentRoute: typeof ApiSitesSiteIdRoute
    }
  }
}

interface ApiSitesSiteIdRouteChildren {
  ApiSitesSiteIdActivityRoute: typeof ApiSitesSiteIdActivityRoute
  ApiSitesSiteIdDevicesRoute: typeof ApiSitesSiteIdDevicesRoute
  ApiSitesSiteIdLocationsRoute: typeof ApiSitesSiteIdLocationsRoute
  ApiSitesSiteIdPagesRoute: typeof ApiSitesSiteIdPagesRoute
  ApiSitesSiteIdPublicViewRoute: typeof ApiSitesSiteIdPublicViewRoute
  ApiSitesSiteIdSourceDetailsRoute: typeof ApiSitesSiteIdSourceDetailsRoute
  ApiSitesSiteIdSourcesRoute: typeof ApiSitesSiteIdSourcesRoute
  ApiSitesSiteIdSummaryRoute: typeof ApiSitesSiteIdSummaryRoute
  ApiSitesSiteIdTimeseriesRoute: typeof ApiSitesSiteIdTimeseriesRoute
  ApiSitesSiteIdRealtimeWsRoute: typeof ApiSitesSiteIdRealtimeWsRoute
}

const ApiSitesSiteIdRouteChildren: ApiSitesSiteIdRouteChildren = {
  ApiSitesSiteIdActivityRoute: ApiSitesSiteIdActivityRoute,
  ApiSitesSiteIdDevicesRoute: ApiSitesSiteIdDevicesRoute,
  ApiSitesSiteIdLocationsRoute: ApiSitesSiteIdLocationsRoute,
  ApiSitesSiteIdPagesRoute: ApiSitesSiteIdPagesRoute,
  ApiSitesSiteIdPublicViewRoute: ApiSitesSiteIdPublicViewRoute,
  ApiSitesSiteIdSourceDetailsRoute: ApiSitesSiteIdSourceDetailsRoute,
  ApiSitesSiteIdSourcesRoute: ApiSitesSiteIdSourcesRoute,
  ApiSitesSiteIdSummaryRoute: ApiSitesSiteIdSummaryRoute,
  ApiSitesSiteIdTimeseriesRoute: ApiSitesSiteIdTimeseriesRoute,
  ApiSitesSiteIdRealtimeWsRoute: ApiSitesSiteIdRealtimeWsRoute,
}

const ApiSitesSiteIdRouteWithChildren = ApiSitesSiteIdRoute._addFileChildren(
  ApiSitesSiteIdRouteChildren,
)

interface ApiSitesRouteChildren {
  ApiSitesSiteIdRoute: typeof ApiSitesSiteIdRouteWithChildren
}

const ApiSitesRouteChildren: ApiSitesRouteChildren = {
  ApiSitesSiteIdRoute: ApiSitesSiteIdRouteWithChildren,
}

const ApiSitesRouteWithChildren = ApiSitesRoute._addFileChildren(
  ApiSitesRouteChildren,
)

interface ApiPublicSlugRouteChildren {
  ApiPublicSlugRealtimeRoute: typeof ApiPublicSlugRealtimeRoute
  ApiPublicSlugSourceDetailsRoute: typeof ApiPublicSlugSourceDetailsRoute
}

const ApiPublicSlugRouteChildren: ApiPublicSlugRouteChildren = {
  ApiPublicSlugRealtimeRoute: ApiPublicSlugRealtimeRoute,
  ApiPublicSlugSourceDetailsRoute: ApiPublicSlugSourceDetailsRoute,
}

const ApiPublicSlugRouteWithChildren = ApiPublicSlugRoute._addFileChildren(
  ApiPublicSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectRoute: CollectRoute,
  LoginRoute: LoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiSitesRoute: ApiSitesRouteWithChildren,
  PublicSlugRoute: PublicSlugRoute,
  ApiAdminAccessRoute: ApiAdminAccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicSlugRoute: ApiPublicSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
